### PR TITLE
Update rjson.js

### PR DESCRIPTION
**Pull request by aleksraiden**
add expose RJSON as module for Node.js

### CODE REVIEW

**Comment by dogada** [comment]
Thanks Alexandr. Do you plan to use RJSON for compressing financial quotes (such data look like ideal candidate for this kind of compression)?

**Comment by aleksraiden** [comment]
Yes, i try to embedded rjson at my server and have 2.75 compress rate. Now  i rewrite some server side and plan to use this at production in the few month... Thanks for the good jobs!

**Comment by dogada** [comment]
Nice to hear. Do you use RJSON with nodejs? I have an idea how to improve RJSON compression of complex repeated data structures like Twitter search results that have a lot of embedded dictionaries. I'm finishing a project now and hope to add this improvement next week.

**Comment by aleksraiden** [comment]
Yea, dictionary is cool, i add this (but very customized) to my app, eg.: if you have at old version     cur:"USD" (9 symbols per field), at now only 1 ( - add numerical code for currency - and delete quotes ")

Yes, one part work at nodejs, second - at browser. One moment is critical - how correct detect, using rjson or no - at result - i want no compress detect, only and at all use RJSON.unpack(data) - and if we have compress, decompress data, if no - data will be returned without any modify

**Comment by aleksraiden** [comment]
P.S, Sorry, english isnt native for me :) but this is good practice )

**Comment by dogada** [comment]
If you will have questions or suggestions related to RJSON, you can send it  to http://www.twitter.com/d0gada Looks like we both are from Ukraine ;)

**Comment by aleksraiden** [comment]
Wow :) чет я ступил ))))) Может Киев? Не нашел паблик информации ) Поставлю пиво/кофе за столь хороший продукт )

**Comment by dogada** [comment]
Не Киев, но когда буду в Киеве, напишу :) Кстати, вчера обновил репозиторий, оформил как nodejs  пакет и добавил скрипт для упаковки/распаковки в командной строке.

**Pull request merged**
